package com.kod.assurancecontracthandler.model

data class Contract(
    val index: Double ,
    val attestation: Any? ="",
    val carteRose: Any? = "0.0",
    val numeroPolice: Any? = "",
    val compagnie: Any? = "",
    val telephone: Any? = null,
    val assure: Any? = "",
    val effet: Any? = null,
    val echeance: Any?= null,
    val puissanceVehicule: Any? = "",
    val mark: Any? = "",
    val immatriculation: Any? = "",
    val categorie: Any? = "1.0",
    val zone: Any? = "C",
    val duree: Any? = null,
    val DTA: Any? = null,
    val PN: Any? = null,
    val ACC: Any? = null,
    val FC: Any? = null,
    val TVA: Any? = null,
    val CR: Any? = null,
    val PTTC: Any? = null,
    val COM_PN: Any? = null,
    val COM_ACC: Any? = null,
    val TOTAL_COM: Any? = null,
    val NET_A_REVERSER: Any? = null,
    val ENCAIS: Any? = null,
    val COMM_LIMBE: Any? = null,
    val COMM_APPORT: Any? = null,
    val APPORTEUR: Any? = null
)
