name: Building the app

on:
  # Would be triggered when a pull request is created.
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout.
        uses: actions/checkout@v3.6.0

      # Set up Java 11 using  AdoptOpenJDK
      - name: Setting up Java.
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'temurin'

      # Grant access to gradlew
      - name: Granting access to gradlew.
        run: chmod +x gradlew

      # Validate the Gradle wrapper
      - name: Build with Gradle.
        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc

      # Run Gradle tasks to build and test the app
      - name: Build and test
        run: ./gradlew build test

      # Run Gradle tasks to build and test the app
      - name: Upload the apk.
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      
      # Send a discord notification that the run was successful.
      - name: Sending success build app discord message.
        uses: fateyan/action-discord-notifier@v1.2.0
        with:
          webhook: https://discord.com/api/webhooks/1151639521377669190/eIyFoD1Lgojgx125cPPcRcSHsAmIMoJpvdJp08sIWhkcm91Cj6ayMgjtL7hG4Az2R1Jp
          message-title: '💪💪💪 safely built app'
          
