name: Building the app

on:
  # Would be triggered when a pull request is created.
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout.
        uses: actions/checkout@v2.5.1

      # Set up Java 11 using  AdoptOpenJDK
      - name: Setting up Java.
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Validate the Gradle wrapper
      - name: Build with Gradle.
        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc

      # Run Gradle tasks to build and test the app
      - name: Build and test
        run: ./gradlew build test

      # Run Gradle tasks to build and test the app
      - name: Upload the apk.
        uses: action/upload-artifact@v3.0.0
        with:
          name: app
          path: app/build/outut/apk/debug/app-debug.apk


